package guess.the.number;

import java.util.Random;
import java.util.Scanner;

/**
 * Simple console game "Guess The Number". The player tries to guess the number
 * generated by the computer. The player can choose the difficulty level: - easy
 * (1) - medium (2) - hard (3) After each game, the player can choose to play
 * again or exit the game.
 */
public class GuessTheNumber_main {

	/**
	 * Program entry point.
	 * 
	 * <p>
	 * Starts a console-based "Guess The Number" game. The player selects a
	 * difficulty level, then tries to guess a randomly generated number. After
	 * finishing a round, the player can choose to play again or exit the game.
	 * <p>
	 * The program validates user input and prevents invalid (non-numeric) values
	 * from crashing the game.
	 * 
	 * @param args
	 */
	public static void main(String[] args) {

		boolean end = false;
		Scanner inputScanner = new Scanner(System.in);

		while (end == false) {

			Random random = new Random();
			int secretNumber;
			int playerGuess = 0;
			int attemptsCount = 0;

			// Choose difficulty level
			while (true) {
				System.out.println("Choose the level (1 | 2 | 3)");
				int level = inputScanner.nextInt();

				if (level == 1) {
					secretNumber = random.nextInt(50) + 1;
					break;

				} else if (level == 2) {
					secretNumber = random.nextInt(500) + 1;
					break;

				} else if (level == 3) {
					secretNumber = random.nextInt(1000) + 1;
					break;

				} else {
					System.out.println("Choose one of the positions" + "\n");
				}
			}

			// game mechanic
			while (true) {

				// Ask the player to guess
				System.out.print("\n" + "Guess the secret number: ");

				// Check if input is an integer
				if (!inputScanner.hasNextInt()) {
					System.out.println("Write only numbers!");
					inputScanner.next(); // remove invalid input
					continue; // restart guessing loop
				}

				// Read player's guess
				playerGuess = inputScanner.nextInt();

				// compare guess with the secret number
				if (playerGuess < secretNumber) {
					System.out.println("Too low");
					attemptsCount++;

				} else if (playerGuess > secretNumber) {
					System.out.println("Too high");
					attemptsCount++;

				} else {
					attemptsCount++;
					System.out.println("Correct!");
					System.out.println("You guessed in " + attemptsCount + " attempts" + "\n" + "\n");
					break; // Exit game mechanic loop
				}

			}

			// play again or stop the game
			boolean wrongInput = false;
			do {

				System.out.print("Do you want to play again? " + "\n");
				String again = inputScanner.next();

				switch (again) {
				case "yes":
					end = false; // Continue the game
					wrongInput = false;
					System.out.println("\n" + "\n");
					break;

				case "no":
					end = true;
					wrongInput = false;
					break;

				default:
					System.out.println("Please choose one of the positions: ");
					wrongInput = true;
				}
			} while (wrongInput == true);
		}
		inputScanner.close();
	}
}
